In [1]:
# Numpy gives the efficent storage
# It provides the better ways of handeling the data for processing
# It is fast and easy to learn
# It relatively uses less memory to store data - KIND OF DYNAMMIC MEMORY ALLOCATION IN C

import numpy as np

In [2]:
myarr = np.array([3,4,5,6], np.int8) #np.int8 -> datatype is int
myarr

array([3, 4, 5, 6], dtype=int8)

In [3]:
myarr[2]

5

In [4]:
myarr.shape

(4,)

In [5]:
myarr[1] = 7 # We can change the element of the array
myarr

array([3, 7, 5, 6], dtype=int8)

**Array Creation : Conversion from other python structure**

In [6]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
listarray.shape # (3,3)
# listarray.size # 9 

(3, 3)

In [8]:
# Adding set
np.array({34,23,35}) # array({34, 35, 23}, dtype=object) -> dtype=object is not always effiecent 

array({34, 35, 23}, dtype=object)

In [9]:
# seros
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# arange
rng = np.arange(15) # It gives the range in the form of numpy array - array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# linspace
lspace = np.linspace(1,50,10) # It gives equally 10 spaces number from 1 to 50 -  array([ 1., 6.44444444, 11.88888889, 17.33333333, 22.77777778, 28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.])
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [12]:
emp = np.empty((4,6)) # It creates the empty array of size of 4 rows and 6 cols - This is done due to efficency
emp

array([[1.51779809e+256, 2.35287091e+251, 1.12320039e+219,
        6.01334635e-154, 3.65284486e+233, 3.99909290e+252],
       [1.09944918e+155, 2.58744404e+161, 2.43207542e-152,
        9.00120658e+223, 1.62691060e+219, 2.44087708e-154],
       [2.12393771e-147, 5.70951435e+228, 6.78875880e+199,
        2.06752737e+161, 2.19993033e-152, 1.73612324e+065],
       [5.28559486e+180, 2.06752737e+161, 1.33856861e-152,
        1.35712977e+166, 4.33593345e+199, 5.70951435e+228]])

In [13]:
emp_like = np.empty_like(lspace) # if we had earlier created the array, so the empty_like will create the array of same size and shape as of the earlier array 
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [14]:
ide = np.identity(45) # It creates the identity matrix of 45X45
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [15]:
rng = np.arange(99) 
rng
rng.reshape((3,33)) # It divided the array into 3 parts of 33 elements (0 to 32) each
# rng.reshape((3,31)) # It gives the error as we cannot divid the array into 3 parts of 31 elements (0 to 30) because we cannot entirely divide 99 by 3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [16]:
# N dim array has n-axis - We start with axis 0 and go to axis n-1. For 2D - no of axis are 2 (Axis 0 and Axis 1), so here rows are Axis 0 and cols are Axis 1
# In !D there is only one axis named Axis 0 

x = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
ar.sum(axis = 0) # add the each row elements of particular column
ar.sum(axis = 1) # add the each col elements of particular row

array([ 6, 15, 24])

In [18]:
ar.T # THIS WILL TRANSPOSE THE ORIGINAL ARRAY

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
# to flat the array and to get all the items
ar.flat
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [20]:
# to get the number of dim
ar.ndim # 2

# Total bytes consumed
ar.nbytes # 36

36

In [21]:
one = np.array([1,3,4,5,2])
one.argmax() # THIS IS THE FUNCTION WHICH GIVES THE INDEX OF THE MAXIMUM ELEMENT
one.argmin() # THIS IS THE FUNCTION WHICH GIVES THE INDEX OF THE MININUM ELEMENT

0

In [22]:
one.argsort() # it return the indices of the array element in which the array could be in sorted order - array([0, 4, 1, 2, 3], dtype=int64)

array([0, 4, 1, 2, 3], dtype=int64)

In [23]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [24]:
ar.argmin() # it returns the min element index - ar[2][2] in this case -> o/p = 8

8

In [25]:
ar.argmax(axis = 0) # IT RETURNS THE MAX ELEMENT IN EVERY COL IN AXIS 0 FORMAT - array([2, 1, 1], dtype=int64)

array([2, 1, 1], dtype=int64)

In [26]:
ar.argmax(axis = 1) # IT RETURNS THE MAX ELEMENT IN EVERY ROW IN AXIS 1 FORMAT - array([2, 2, 0], dtype=int64)

array([2, 2, 0], dtype=int64)

In [27]:
ar.argsort() # it gives sorting according to the axis 1

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [28]:
ar.argsort(axis = 0) # it gives sorting according to the axis 0

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [29]:
ar.argsort(axis = 1) # it gives sorting according to the axis 1

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [30]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [33]:
ar + ar2 # Addition

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [34]:
ar * ar2 # Multiplication

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [35]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [36]:
ar.sum()

29

In [37]:
ar.max()

7

In [38]:
np.where(ar > 5) #it returns the coordinates of the element for which the element is > 5 i.e coordinates of 6 & 7

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [39]:
type(np.where(ar > 5)) # type is TUPLE

tuple

In [40]:
np.count_nonzero(ar) # count of non zero element

8

In [41]:
np.nonzero(ar) # It returns the coordinates of the non zero element in 2 differnt tuples. First tuple represent the X coordinate and 2nd tuple, the Y Coordinate

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

**Why nparray takes less size than python array**

In [42]:
import sys

In [43]:
py_arr = [0,4,55,2] # python array

In [44]:
np_arr = np.array(py_arr) # np array

In [45]:
sys.getsizeof(1) * len(py_arr) # Getting the size of each element of python array and multiplying it with the len to get the size of python array

112

In [46]:
np_arr.itemsize * np_arr.size # Getting the size of each element of numpy array and multiplying it with the len to get the size of numpy array
# SO WE CAN SEE THAT PYTHON ARRAY IS TAKING 112 BYTES OF SIZE WHILE NUMPY ARRAY TAKES 16 BYTES OF SIZE (VERY MUCH SAVING SPACE)

16